// syntax highlighting functions from skylighting:
/* Function definitions for syntax highlighting generated by skylighting: */
#let EndLine() = raw("\n")
#let Skylighting(fill: none, number: false, start: 1, sourcelines) = {
   let blocks = []
   let lnum = start - 1
   let bgcolor = none
   for ln in sourcelines {
     if number {
       lnum = lnum + 1
       blocks = blocks + box(width: if start + sourcelines.len() > 999 { 30pt } else { 24pt }, text(fill: rgb("#aaaaaa"), [ #lnum ]))
     }
     blocks = blocks + ln + EndLine()
   }
   block(fill: bgcolor, blocks)
}
#let AlertTok(s) = text(weight: "bold",fill: rgb("#ff0000"),raw(s))
#let AnnotationTok(s) = text(weight: "bold",style: "italic",fill: rgb("#60a0b0"),raw(s))
#let AttributeTok(s) = text(fill: rgb("#7d9029"),raw(s))
#let BaseNTok(s) = text(fill: rgb("#40a070"),raw(s))
#let BuiltInTok(s) = text(fill: rgb("#008000"),raw(s))
#let CharTok(s) = text(fill: rgb("#4070a0"),raw(s))
#let CommentTok(s) = text(style: "italic",fill: rgb("#60a0b0"),raw(s))
#let CommentVarTok(s) = text(weight: "bold",style: "italic",fill: rgb("#60a0b0"),raw(s))
#let ConstantTok(s) = text(fill: rgb("#880000"),raw(s))
#let ControlFlowTok(s) = text(weight: "bold",fill: rgb("#007020"),raw(s))
#let DataTypeTok(s) = text(fill: rgb("#902000"),raw(s))
#let DecValTok(s) = text(fill: rgb("#40a070"),raw(s))
#let DocumentationTok(s) = text(style: "italic",fill: rgb("#ba2121"),raw(s))
#let ErrorTok(s) = text(weight: "bold",fill: rgb("#ff0000"),raw(s))
#let ExtensionTok(s) = text(raw(s))
#let FloatTok(s) = text(fill: rgb("#40a070"),raw(s))
#let FunctionTok(s) = text(fill: rgb("#06287e"),raw(s))
#let ImportTok(s) = text(weight: "bold",fill: rgb("#008000"),raw(s))
#let InformationTok(s) = text(weight: "bold",style: "italic",fill: rgb("#60a0b0"),raw(s))
#let KeywordTok(s) = text(weight: "bold",fill: rgb("#007020"),raw(s))
#let NormalTok(s) = text(raw(s))
#let OperatorTok(s) = text(fill: rgb("#666666"),raw(s))
#let OtherTok(s) = text(fill: rgb("#007020"),raw(s))
#let PreprocessorTok(s) = text(fill: rgb("#bc7a00"),raw(s))
#let RegionMarkerTok(s) = text(raw(s))
#let SpecialCharTok(s) = text(fill: rgb("#4070a0"),raw(s))
#let SpecialStringTok(s) = text(fill: rgb("#bb6688"),raw(s))
#let StringTok(s) = text(fill: rgb("#4070a0"),raw(s))
#let VariableTok(s) = text(fill: rgb("#19177c"),raw(s))
#let VerbatimStringTok(s) = text(fill: rgb("#4070a0"),raw(s))
#let WarningTok(s) = text(weight: "bold",style: "italic",fill: rgb("#60a0b0"),raw(s))
